name: Sync folders to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get list of folders
        run: |
          folders=$(find . -mindepth 1 -maxdepth 1 -type d ! -name ".*" -exec basename {} \;)
          echo "FOLDERS<<EOF" >> $GITHUB_ENV
          echo "$folders" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Clear folders
        run: |
          rm -rf *

      - name: Clone folders to gh-pages
        run: |
          git worktree add main main
          FOLDERSARRAY=($FOLDERS)

          for folder in "${FOLDERSARRAY[@]}"; do
            echo "Copying Folder: $folder"

            if [ ! -f "./main/$folder/.external" ]; then
              cp -r ./main/$folder .
              git add $folder
            fi
          done

          git worktree remove main --force

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Sync all folders into gh-pages" || echo "No changes to commit"
          git push origin gh-pages
